### ISSUE TITLE
core.test.suite: `Setup()` and `TearDown()` should be called `SetupTest` and `TearDownTest` respectively

### ISSUE THREAD

**Issue by alcortesm** [src-d/core#24]
As a developer that uses the test package from this repo, I want `suite.Setup()` and `suite.TearDown()` to be called `suite.SetupTest` and `suite.TearDownTest` as to avoid having to define them myself from scratch.

This change will simplify the code using this library but will require an API breaking change, therefor a new version.

**Comment by smola** [comment]
Closing, since this is now deprecated in favor of core-retrieval and other projects.
